version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'spotsync_app'
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: ".env"
    volumes:
      - './src:/app/src'
      - './test:/app/test'
      - './prisma:/app/prisma'
      - './nest-cli.json:/app/nest-cli.json'
      - './tsconfig.json:/app/tsconfig.json'
      - './tsconfig.build.json:/app/tsconfig.build.json'
      - './package.json:/app/package.json'
      - './.prettierrc:/app/.prettierrc'
      - './.eslintrc.js:/app/.eslintrc.js'
    networks:
      - net
  db:
    image: 'postgres:latest'
    container_name: 'spotsync_db'
    ports:
      - 5436:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data/
    networks:
      - net
    env_file: ".env"
networks:
  net:
    driver: bridge