version: '3'
services:
  db:
    image: 'postgres:latest'
    container_name: 'spotsync_db'
    ports:
      - 5436:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data/
    networks:
      - postgres-network
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
networks:
  postgres-network:
    driver: bridge