version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'spotsync_app'
    ports:
      - 3001:3000
    depends_on:
      - db
      - redis
      - mailhog
    env_file: ".env"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - net
  db:
    image: 'postgres:latest'
    container_name: 'spotsync_db'
    ports:
      - 5436:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data/
    networks:
      - net
    env_file: ".env"
  redis:
    image: 'redis:latest'
    container_name: 'spotsync_redis'
    ports:
      - 6379:6379
    networks:
      - net
    env_file: ".env"
  mailhog:
    image: mailhog/mailhog
    container_name: 'spotsync_mailhog'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - net
    env_file: ".env"
networks:
  net:
    driver: bridge