version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'spotsync_app'
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - GOOGLE_MAPS_SECRET_KEY=${GOOGLE_MAPS_SECRET_KEY}
      - DATABASE_URL=${DATABASE_DRIVER}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    volumes:
      - './src:/app/src'
      - './test:/app/test'
      - './prisma:/app/prisma'
      - './nest-cli.json:/app/nest-cli.json'
      - './tsconfig.json:/app/tsconfig.json'
      - './tsconfig.build.json:/app/tsconfig.build.json'
      - './package.json:/app/package.json'
      - './.prettierrc:/app/.prettierrc'
      - './.eslintrc.js:/app/.eslintrc.js'
    networks:
      - net
  db:
    image: 'postgres:latest'
    container_name: 'spotsync_db'
    ports:
      - 5436:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data/
    networks:
      - net
    environment:
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
networks:
  net:
    driver: bridge