services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'spotsync_app'
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: ".env"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - net
  db:
    image: 'postgres:latest'
    container_name: 'spotsync_db'
    ports:
      - 5436:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data/
    networks:
      - net
    env_file: ".env"
networks:
  net:
    driver: bridge